- name: Compilar todos los códigos C++
  run: |
    mkdir -p build
    for dir in Laboratorio*; do
      echo "Compilando $dir..."
      mkdir -p "build/$dir"
      for file in "$dir"/*.cpp; do
        filename=$(basename "$file" .cpp)
        g++ -std=c++17 -Wall -Wextra -o "build/$dir/$filename" "$file"
      done
    done

